require "user.plugins"

require "user.options"
require "user.keymaps"
require "user.colorscheme"

require "user.cmp"
require "user.lsp"
require "user.plug-colorizer"
require "user.nvim-tree"
require "user.lualine"
require "user.treesitter"
require "user.comment"
require "user.indent-lines"
require "user.gitsigns"
require "user.formatter"
